config/routes.rb
BlrTraffic::Application.routes.draw do

  
  root :to => "home#index"

  match "/offences/:id" => "offence_report#offences"
  match "/offence/:id/:time" => "offence_report#report"
  
  resources :feedback, :only => [:index,:new, :create]
  resources :video, :only => [:index, :new, :create, :destroy]
  
end

app/models/feedback.rb
class Feedback < ActiveRecord::Base
  
end

app/models/http_gateway.rb
class HttpGateway
  include HTTParty
  format :xml
  
  def self.get_request(url)
    get(url)
  end
  
end

app/models/offence.rb
class Offence < ActiveRecord::Base
  belongs_to :video
  
end

app/models/video.rb
class Video < ActiveRecord::Base
  has_many :offences, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/feedback_controller.rb
class FeedbackController < ApplicationController
  def new
    @feedback = Feedback.new
  end
  
  def create
    @feedback = Feedback.new(params[:feedback])
    @feedback.ip = request.remote_ip
    @feedback.save!
    flash[:saved] = "Thanks for your feedback. Its has been saved in our system."
    redirect_to new_feedback_url
  end
  
  def index
    @feedbacks = Feedback.all
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  
  def index
    @video = Video.first
    @feedback = Feedback.new
  end
  
end

app/controllers/offence_report_controller.rb
class OffenceReportController < ApplicationController
  
  def report
    video = Video.find(params[:id]) || not_found
    Offence.create!(:time => params[:time], :ip => request.remote_ip, :video => video)
    render :text => "success", :layout => false
  end
  
  def offences
    video = Video.find(params[:id]) || not_found
    @offences = video.offences.order(:time).group(:time).count
    logger.info @offences.inspect
    normalize
  end
  
  private
  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end
  
  def normalize
    @offences.keys.each do |time|
      if @offences[time -1] then
        @offences[time -1] += @offences[time]
        @offences.delete(time)
      end
    end
    
  end
end

app/controllers/video_controller.rb
class VideoController < ApplicationController
  def new
    @video = Video.new
  end
  
  def create
    @video = Video.new(params[:video])
    @video.save!
    flash[:saved] = "Your video has been saved"
    redirect_to new_video_url
  end
  
  def index
    @videos = Video.all
  end
  
  def destroy
    @video = Video.find(params[:id])
    @video.destroy
    flash[:saved] = "Your video has been deleted"
    redirect_to :action => :index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  BASE_URL = "https://gdata.youtube.com/feeds/api/videos/"
  
  def get_view_count(video)
    video_id = video.youtube_link.split("=").last
    response = HttpGateway.get_request(BASE_URL + video_id)
    response["entry"]["statistics"]["viewCount"]
  end
  
  def video_js_link(video)
    video_id = video.youtube_link.split("=").last
    "http://www.youtube.com/v/" + video_id + "?enablejsapi=1&playerapiid=ytplayer&version=3"
  end
  
  def no_of_offences(video)
    result = video.offences.group(:time).count
    result.size
  end
end

app/views/feedback/index.html.erb
<div id="feedbacks">
	<% @feedbacks.each do |feedback| %>
		<div id="feedback <%= feedback.id %> ">
			<p>
				From : <%= feedback.name %>
			</p>	
			<p>
				email : <%= feedback.email %>
			</p>
			<p>
				ip : <%= feedback.ip %>
			</p>
			<p>
				<%= feedback.comment %>
			</p>		
		</div>
		<hr/>	
	<% end %>
</div>	

app/views/feedback/new.html.erb
<div id="saved" background-color:"yellow">
	<%= flash[:saved] %>
</div>	

<div id="feedback_form">
	<%= form_for(:feedback, :url => {:action => :create}) do |form| %>
		<p>
			<%= form.label :name %>
			<%= form.text_field :name, :placeholder => "Your Name" %>
		</p>
		
		<p>
			<%= form.label :email %>
			<%= form.text_field :email, :placeholder => "Your email" %>
		</p>	
	
		<p>
			<%= form.label :comment %>
			<%= form.text_area :comment, :rows => 4, :cols => 40 %>
		</p>
		
		<p>
			<%= form.submit "Submit" %>
		</p>
	<% end %>
	
</div>

app/views/home/_about.html.erb
    <div class="span7">
      <h2>About us</h2>
       <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
       <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui. Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
       <p>Donec id elit non mi porta gravida at eget metus. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Etiam porta sem malesuada magna mollis euismod. Donec sed odio dui.</p>
      <p><a class="btn" href="#">Learn more &raquo;</a></p>
      <h2>Contact us</h2>
       <p>email: <a href="mailto:info@controlroom.in">info@controlroom.in</a></p>
   </div>

app/views/home/_feedback.html.erb
<%= javascript_tag do %>
	
	function onSubmit(){
		$("#saved").text("Your feedback has been entered into our system");
		$(".feedback_form").submit();	
	};
	
<% end %>


<div class="span5 Feedback">

	<div id="feedback_form">
		<%= form_for(:feedback, :url => {:controller => :feedback, :action => :create}, :remote => true, :class => "form-horizontal", :id => "feedback_form") do |form| %>
		<legend>Feedback</legend>
		<div id="saved"></div>

	  	<fieldset>
			<div class="control-group">
			  <%= form.label :name, :id => "input01", :class => "control-label" %>
			  <div class="controls">
				<%= form.text_field :name, :id => "input01", :class => "input-xlarge", :placeholder => "anonymous" %>
		      </div>
		    </div>
	
			<div class="control-group">
			  <%= form.label :name, :id => "input02", :class => "control-label" %>
			  <div class="controls">
				<%= form.text_field :name, :id => "input02", :class => "input-xlarge", :placeholder => "yourmail@example.com" %>
		      </div>
		    </div>
	
		    <div class="control-group">
		      <%= form.label :comment %>
		      <div class="controls">
		        <%= form.text_area :comment, :rows => 3, :id => "textarea" %>
		      </div>
		    </div>
	    	<div class="form-actions">
				<%= form.submit "Submit", :onClick => "onSubmit();" %>

			</div>
		</fieldset>
		
		<% end %>

	</div>

</div>

app/views/home/index.html.erb
<%= javascript_tag do -%>
	var ytplayer;
	
	function onYouTubePlayerReady(playerId) {
		ytplayer = document.getElementById("myytplayer");
	}

	function reportOffence(url){
		var time_of_offence = ytplayer.getCurrentTime();
		var url = "/offence/" + <%= @video.id %> + "/" + time_of_offence;
		$.post(url, function(data) {
		  var offences ="<li><span class=\"label label-important\">" +time_of_offence + "</span></li>";
		  $('#reportedOffences').append(offences);
		});
	}

	var params = { allowScriptAccess: "always" };
    var atts = { id: "myytplayer" };
    swfobject.embedSWF("<%= video_js_link(@video) %>",
                       "ytapiplayer", "600", "400", "8", null, null, params, atts);

<% end -%>


<div class="container">
	<div class="row hero-section">
		<div class="span12">
			<div class="tabbable tabs-left">
    			<ul class="nav nav-tabs">
  				    <li class="active"><a href="#DemoTab" data-toggle="tab">Demo</a></li>
   				   <li><a href="#ReportTab" data-toggle="tab">Play</a></li>
   				 </ul>
		        <div class="tab-content">
		          <div class="tab-pane active" id="#ReportTab">
		            <div class="row">
		            	<div class="span5">
		            		<div class="video" id="ytapiplayer"></div>
		            	</div>
		            	<div class="span4 report">
                  <div class="action">

                    <button class="btn btn-primary btn-large" onClick="reportOffence();return false;">Catch me!</button>
                  </div>
		            	</div>
		            </div>
              <div class="row">
                <div class="time">
                  <ul id="reportedOffences">

                  </ul>
                </div>
              </div>
		          </div>
		          <div class="tab-pane" id="#DemoTab">
		          </div>
		        </div>
		      </div>
		</div>
	</div>
	<div class="border"></div>
  <div class="row">
	
  	<%= render :partial => "about" %>

  	<%= render :partial => "feedback" %>
  </div>
  <hr>

  <footer>
    <p>&copy; Control Room 2012</p>
  </footer>
</div>
	
	

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Bangalore Traffic Experiment</title>	
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/swfobject/2.2/swfobject.js" %>
  <%= javascript_include_tag "https://www.google.com/jsapi" %>
  <%= csrf_meta_tags %>
	
	
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-33533686-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>	
	
</head>


<body>
	    <div class="navbar navbar-fixed-top">
	      <div class="navbar-inner">
	        <div class="container">
	          <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	            <span class="icon-bar"></span>
	          </a>
	          <a class="brand" href="#">The Bangalore Traffic Experiment</a>
	          <div class="nav-collapse">
	          </div><!--/.nav-collapse -->
	        </div>
	      </div>
	    </div>

<%= yield %>

</body>
</html>

app/views/offence_report/offences.html.erb
<%= javascript_tag do -%>

  google.load("visualization", "1", {packages:["corechart"]});
  google.setOnLoadCallback(drawChart);
  function drawChart() {
    var data = google.visualization.arrayToDataTable([
	  ['Time', 'Offences Reported'],
	  <% @offences.each do |k, v| %>
		[<%= k %>, <%= v %>],
      <% end %>
	  ]);


    var options = {
      title: 'Offences'
    };

    var chart = new google.visualization.ColumnChart(document.getElementById('offences_chart'));
    chart.draw(data, options);
  }
<% end -%>


<div id="offences_chart">
</div>

app/views/offence_report/report.html.erb
Done

app/views/video/index.html.erb
<div id="video">
	<% @videos.each do |video| %>
		<div id="video <%= video.id %> ">
			<p>
				Video : <%= video.name %>
			</p>	
			<p>
				youtube : <%= video.youtube_link %>
			</p>	
			<p>	
			<%= button_to "Delete", video_path(video), :method => "delete" %>	

			</p>
		</div>
		<hr/>	
	<% end %>
</div>

app/views/video/new.html.erb
<div id="saved" background-color:"yellow">
	<%= flash[:saved] %>
</div>	

<div id="video_form">
	<%= form_for(:video, :url => {:action => :create}) do |form| %>
		<p>
			<%= form.label :name %>
			<%= form.text_field :name, :placeholder => "Video name" %>
		</p>
		
		<p>
			<%= form.label :youtube_link %>
			<%= form.text_field :youtube_link, :placeholder => "youtube link" %>
		</p>	
		
		<p>
			<%= form.submit "Submit" %>
		</p>
	<% end %>
	
</div>